
default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: dannybenshi
 password: DannyPro123

development:
  <<: *default
  database: budjet-db-dev
test:
  <<: *default
  database: budjet-db-test

production:
  <<: *default
  database: db/production.sqlite3
